### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/market-maker#3]

**Comment by AniketNS** [comment]
Do you want docker file created for this project?

**Comment by 4TT1L4** [comment]
@AniketNS 
> Do you want docker file created for this project?
Yes. We needed a Dockerfile, so we could have a setup that is similar like the one we have for the Smart Order Router. There is a standalone Dockerfile that can be used to run the tool. It is also used in the CI pipeline, but this is also used in the Dockercompose, which is used to setup all the dependencies; including Kupo and the Cardano Node.

The Dockerfile had been added in the following PR:
 - https://github.com/geniusyield/market-maker/pull/4
